### ISSUE TITLE
Unhandled stream error in pipe

### ISSUE THREAD

**Issue by TheSlowGrowth** [fiam/arm-none-eabi-gcc#17]
Occasionally, I get failed pipeline runs with this message:
```
Run fiam/arm-none-eabi-gcc@v1
(node:1671) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
downloading gcc 9-2019-q4 from https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2
extracting to /tmp/tmp-1671f5TW4SgJD7H7/gcc-9-2019-q4
internal/streams/legacy.js:59
      throw er; // Unhandled stream error in pipe.
      ^

TypeError: Cannot read property '0' of undefined
    at f (/home/runner/work/_actions/fiam/arm-none-eabi-gcc/v1/dist/index.js:21619:34)
    at Object.module.exports.370.bzip2.decompress (/home/runner/work/_actions/fiam/arm-none-eabi-gcc/v1/dist/index.js:12282:28)
    at decompressBlock (/home/runner/work/_actions/fiam/arm-none-eabi-gcc/v1/dist/index.js:25151:29)
    at decompressAndQueue (/home/runner/work/_actions/fiam/arm-none-eabi-gcc/v1/dist/index.js:25168:20)
    at Stream.end (/home/runner/work/_actions/fiam/arm-none-eabi-gcc/v1/dist/index.js:25203:17)
    at _end (/home/runner/work/_actions/fiam/arm-none-eabi-gcc/v1/dist/index.js:13066:9)
    at Stream.stream.end (/home/runner/work/_actions/fiam/arm-none-eabi-gcc/v1/dist/index.js:13075:5)
    at PassThrough.onend (_stream_readable.js:692:10)
    at Object.onceWrapper (events.js:299:28)
    at PassThrough.emit (events.js:210:5)
    at endReadableNT (_stream_readable.js:1184:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

This may be related to #11.

**Comment by nerdCopter** [comment]
From my understanding and experience, the downloads are not finishing and getting truncated mid-stream as if the stream is just dropped.  I believe this to be the source for both our issues. However my ticket has gone unanswered.  i updated my original with a working link; however, i may rebuild the branch.

edit: i had not noticed some new retry logic here: https://github.com/fiam/arm-none-eabi-gcc/commit/abeabe73714f61c325d323a4247787efcdafe906
my `retry_timeout` may be defunct/obsolete.
